version: '3.8'

include:
  - docker-compose.base.yml

services:
  quadruped_robot_dev:
    build:
      context: ..
      dockerfile: docker/development/Dockerfile
    image: quadruped_robot_dev
    container_name: quadruped_robot_dev
    <<: *common-config
    volumes:
      - ../src:/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    devices:
      - /dev/dri:/dev/dri
      - /dev/video0:/dev/video0
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    privileged: true
    command: /bin/bash
