slam_toolbox:
  ros__parameters:
    use_sim_time: true
    map_frame: map
    base_frame: base_link
    odom_frame: odom
    scan_topic: /svan/scan
    resolution: 0.05
    max_laser_range: 30.0
    minimum_time_interval: 1.0
