version: '1'
services:
  ros2_realsense:
    image: osrf/ros:humble-desktop
    container_name: ros2_realsense_dev
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - ./ros2_ws:/root/ros2_ws
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    network_mode: host
    privileged: true
    command: >
      bash -c "
        apt-get update && apt-get install -y \
          ros-humble-realsense2-camera \
          ros-humble-realsense2-description \
          && source /opt/ros/humble/setup.bash \
        && bash"

  realsense_viewer:
    image: intelrealsense/librealsense:latest
    container_name: realsense_viewer
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    network_mode: host
    privileged: true
    command: realsense-viewer