# docker/nav2/docker-compose.yml
version: '3'

# services:
#   ros2_nav2:
#     build:
#       context: .
#       dockerfile: ros2-nav2-dockerfile
#     image: ros2_nav2:latest
#     command: tail -f /dev/null
# version: '3'

services:
  ros2_nav2:
    build:
      context: .
      dockerfile: ros2-nav2-dockerfile
      args:
        BASE_IMAGE: ros2_base:latest
    image: ros2_nav2:latest
    volumes:
      - ../../src:/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
    privileged: true
    # keep container running
    command: tail -f /dev/null
    # command: >
    #   bash -c "
    #     source /opt/ros/humble/setup.bash &&
    #     cd /ros2_ws &&
    #     colcon build &&
    #     source install/setup.bash &&
    #     bash"
